stages:
  - build
  - release

build_and_pack:
  stage: build
  image: node:22
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull-push

  script:
    - echo "Installing dependencies..."
    - npm ci

    - echo "Packing..."
    - npm pack

  artifacts:
    paths:
      - '*.tgz'
      - '*.zip'
    expire_in: 1 week

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/
  script:
    - echo "Preparing release..."
    - |
      RELEASE_DESCRIPTION="Релиз создан для тега $CI_COMMIT_TAG."
      if [ -n "$CI_COMMIT_TAG_MESSAGE" ]; then
        RELEASE_DESCRIPTION="$RELEASE_DESCRIPTION"$'\n\n'"Сообщение тега:"$'\n'"$CI_COMMIT_TAG_MESSAGE"
      fi
      RELEASE_DESCRIPTION="$RELEASE_DESCRIPTION"$'\n\n'"Файлы сборки прикреплены как артефакты."

    - release-cli create --name "Release $CI_COMMIT_TAG" \
      --tag-name $CI_COMMIT_TAG \
      --description "$RELEASE_DESCRIPTION" \
      --assets-path "*.tgz" \
      --assets-path "*.zip"
  needs:
    - job: build_and_pack
      artifacts: true

workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
