stages:
  - build
  - release

variables:
  ARTIFACT_NAME: ''

cache:
  paths:
    - node_modules/

pack:
  stage: build
  image: node:lts
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/
      when: on_success
    - when: manual
      allow_failure: false
  before_script:
    - npm ci
  script:
    - npm pack
    - export ARTIFACT_NAME=$(ls *.tgz)
    - echo "ARTIFACT_NAME=${ARTIFACT_NAME}" > artifact.env
  artifacts:
    paths:
      - '*.tgz'
    reports:
      dotenv: artifact.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: ['pack']
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v/
      when: on_success
    - when: manual
      exists: [tags]
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
  release:
    name: '$CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: |
      Release $CI_COMMIT_TAG created automatically.
      Includes bundled library package.
    assets:
      links:
        - name: '${ARTIFACT_NAME}'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/${ARTIFACT_NAME}'
